# Synthetic data from knowledge

References:

* [Nemotron-CC](https://arxiv.org/abs/2412.02595v2)
* [BeyondWeb](https://blog.datologyai.com/beyondweb/)
* [Kimi K2](https://arxiv.org/abs/2507.20534)

In [1]:
from pathlib import Path

OUTPUT_DIR = Path("output/synthetic/v2")
INPUT_ROOT_DIR = Path("output/wiki")
MIN_CHUNK_SIZE = 256
CHUNK_SIZE = 1024

INPUT_DIRS = [
    INPUT_ROOT_DIR,
    INPUT_ROOT_DIR / "fandom",
    INPUT_ROOT_DIR / "fandom/crawl/luoghi",
    INPUT_ROOT_DIR / "fandom/crawl/personaggi",
    INPUT_ROOT_DIR / "fandom/crawl/personaggi/amici",
    INPUT_ROOT_DIR / "fandom/crawl/personaggi/evroniani",
    INPUT_ROOT_DIR / "fandom/crawl/personaggi/nemici",
    INPUT_ROOT_DIR / "fandom/crawl/personaggi/starcorp",
    INPUT_ROOT_DIR / "fandom/crawl/personaggi/xerbiani",
    INPUT_ROOT_DIR / "fandom/crawl/storie/storie-di-pk-pkna",
    INPUT_ROOT_DIR / "fandom/crawl/tecnologia",
    INPUT_ROOT_DIR / "manual",
]
INPUT_DOCS = sorted([path for d in INPUT_DIRS for path in d.glob("*.md")])

INPUT_MODEL_CONVERSATIONS = Path("output/dataset/dspy-dataset.csv")

## Chunking

In [2]:
from markdown_it import MarkdownIt


def split_markdown(md_text: str) -> list[str]:
    md = MarkdownIt()
    tokens = md.parse(md_text)

    chunks = []
    current = []
    for i, tok in enumerate(tokens):
        if tok.type == "heading_open":
            # flush previous chunk
            if current:
                chunks.append("".join(current))
                current = []
        # reconstruct token text
        if tok.type == "inline":
            current.append(tok.content + "\n")
        elif tok.type.endswith("_open") or tok.type.endswith("_close"):
            # keep markup like ###, code fences, list markers
            current.append(tok.markup + "\n")
        elif tok.type == "fence":
            current.append(f"{tok.markup}{tok.info}\n{tok.content}{tok.markup}\n")
        elif tok.content:
            current.append(tok.content + "\n")

    if current:
        chunks.append("".join(current))

    return chunks

In [3]:
with open("output/wiki/issues.md") as f:
    issues_md = f.read()

chunks = split_markdown(issues_md)

In [4]:
with open("output/wiki/uno.md") as f:
    uno_md = f.read()

tokens = MarkdownIt().parse(uno_md)
set(token.type for token in tokens)

{'bullet_list_close',
 'bullet_list_open',
 'heading_close',
 'heading_open',
 'inline',
 'list_item_close',
 'list_item_open',
 'paragraph_close',
 'paragraph_open'}

In [5]:
from dataclasses import dataclass, field
from collections.abc import Iterator
from markdown_it import MarkdownIt


@dataclass
class Heading:
    level: int
    title: str

    @classmethod
    def from_token(cls, tag: str, content: str) -> "Heading":
        level = int(tag[1:])
        return Heading(level=level, title=content)


@dataclass
class Headings:
    lst: list[Heading] = field(default_factory=list)

    def __str__(self) -> str:
        return "\n\n".join(f"{'#' * h.level} {h.title}" for h in self.lst) + "\n"

    def add(self, heading: Heading):
        # Remove any headings at the same or deeper level
        while self.lst and self.lst[-1].level >= heading.level:
            self.lst.pop()
        self.lst.append(heading)

    def merge(self, other: "Headings") -> "Headings":
        """Merge two Headings lists, keeping the deepest headings."""
        res = Headings(lst=self.lst.copy())
        for heading in other.lst:
            res.add(heading)
        return res


@dataclass
class Segment:
    """A text segment with all the headings in it."""

    headings: Headings = field(default_factory=Headings)
    text: str = ""


def iter_markdown_segments(txt: str) -> Iterator[Segment]:
    lines = txt.splitlines(keepends=True)
    tokens = MarkdownIt().parse(txt)
    segment_headings: Headings = Headings()
    segment_begin = 0
    i = 0

    while i < len(tokens):
        match tokens[i].type:
            case "heading_open":
                h = Heading.from_token(tag=tokens[i].tag, content=tokens[i + 1].content)
                segment_headings.add(h)
                i += 2

            case "paragraph_open":
                _, end = tokens[i].map or []
                # If the inline element is empty, skip it
                if tokens[i + 1].content.strip() == "":
                    i += 3
                    continue

                text = "".join(lines[segment_begin:end])
                yield Segment(headings=segment_headings, text=text)
                i += 2
                segment_begin = end
                segment_headings = Headings()

            case "fence":
                _, end = tokens[i].map or []
                text = "".join(lines[segment_begin:end])
                yield Segment(headings=segment_headings, text=text)
                i += 1
                segment_begin = end
                segment_headings = Headings()

            case _:
                i += 1


# Tests
md = """# This is the title

Body text with **bold** and _italic_ and a [link](http://example.com).

## This is a subheading

### This is a sub-subheading

Another paragraph, with:

- a bullet point
- another bullet point
  - a nested bullet point
- last bullet point

```java
some code
```

A paragraph
"""

[s for s in iter_markdown_segments(md)]

[Segment(headings=Headings(lst=[Heading(level=1, title='This is the title')]), text='# This is the title\n\nBody text with **bold** and _italic_ and a [link](http://example.com).\n'),
 Segment(headings=Headings(lst=[Heading(level=2, title='This is a subheading'), Heading(level=3, title='This is a sub-subheading')]), text='\n## This is a subheading\n\n### This is a sub-subheading\n\nAnother paragraph, with:\n'),
 Segment(headings=Headings(lst=[]), text='\n- a bullet point\n'),
 Segment(headings=Headings(lst=[]), text='- another bullet point\n'),
 Segment(headings=Headings(lst=[]), text='  - a nested bullet point\n'),
 Segment(headings=Headings(lst=[]), text='- last bullet point\n'),
 Segment(headings=Headings(lst=[]), text='\n```java\nsome code\n```\n'),
 Segment(headings=Headings(lst=[]), text='\nA paragraph\n')]

In [6]:
def compact_markdown_segments(
    seq: Iterator[Segment],
    min_length: int = 256,
    max_length: int = 2048,
) -> list[Segment]:
    compacted = []
    curr = Segment()

    for seg in seq:
        if len(curr.text) < min_length or len(curr.text) + len(seg.text) <= max_length:
            # merge segments if the current is too short,
            # or if the combined length is within limits
            curr.text += seg.text
            curr.headings = curr.headings.merge(seg.headings)
        else:
            compacted.append(curr)
            curr = Segment(
                headings=curr.headings.merge(seg.headings),
                text=str(curr.headings) + seg.text,
            )

    if len(curr.text) > min_length:
        compacted.append(curr)

    return compacted


def markdown_segments(
    txt: str, min_length: int = 256, max_length: int = 2048
) -> list[str]:
    return [
        seg.text
        for seg in compact_markdown_segments(
            iter_markdown_segments(txt), min_length, max_length
        )
    ]


markdown_segments(md, min_length=10, max_length=128)

['# This is the title\n\nBody text with **bold** and _italic_ and a [link](http://example.com).\n',
 '# This is the title\n\n## This is a subheading\n\n### This is a sub-subheading\n\nAnother paragraph, with:\n\n- a bullet point\n',
 '# This is the title\n\n## This is a subheading\n\n### This is a sub-subheading\n- another bullet point\n  - a nested bullet point\n',
 '# This is the title\n\n## This is a subheading\n\n### This is a sub-subheading\n- last bullet point\n\n```java\nsome code\n```\n',
 '# This is the title\n\n## This is a subheading\n\n### This is a sub-subheading\n\nA paragraph\n']

In [7]:
with open("output/wiki/uno.md") as f:
    uno_md = f.read()

uno_seg = markdown_segments(uno_md, min_length=128, max_length=1024)
uno_seg

["# Uno (personaggio)\n\nUno è uno dei personaggi principali della serie a fumetti Disney Italia di PK (PK - Paperinik New Adventures, PK², PK - Pikappa e PK - Nuova era).\n\n## Biografia\n\nSi tratta di un'intelligenza artificiale creata da Everett Ducklair. È in grado di controllare in ogni sua parte la Ducklair Tower, che ne costituisce il corpo centrale (tanto da presentarsi a Paperinik dicendo di essere a tutti gli effetti il palazzo), di svolgere calcoli di estrema difficoltà e di introdursi grazie alle sue superiori capacità nelle reti informatiche convenzionali più protette. Controlla anche la grande parte dei marchingegni costruiti da Ducklair.\n",
 "# Uno (personaggio)\n\n## Biografia\n\nÈ il più valido aiuto di Paperinik, di cui conosce l'identità segreta. L'aspetto con cui si presenta agli umani è molto simile al viso di Everett Ducklair, solitamente presentato in forma di ologramma all'interno di una sfera verde. Il suo acerrimo nemico è Due, la crudele intelligenza artificiale di back-up, creata da Everett per subentrargli in caso di grave malfunzionamento e totalmente suo pari. Due si rivelerà essere uno dei nemici più pericolosi di Pikappa e di Uno, e soprattutto uno dei più coriacei.\n\nQuando Uno si stufa dell'arredamento della Ducklair Tower, lo modifica senza preavviso (creando non pochi disagi a chi si trova nel mezzo della ristrutturazione, che in un batter d'occhio possono ritrovarsi dal salone a un angusto sgabuzzino). Nonostante possa sondare tutto il Sistema Solare, Uno si sente prigioniero della torre, non potendo muoversi (come fanno invece gli altri esseri pensanti).\n",
 '# Uno (personaggio)\n\n## Biografia\n\nUno non è alimentato dalla normale rete elettrica della Ducklair Tower e per questo non si "spegne" nemmeno in caso di blackout dell\'intera Paperopoli.\n\nNel XXIII secolo, con l\'aiuto di Ducklair, assorbe una parte della personalità di Due e prende possesso di un corpo sintetico antropomorfo, evolvendo in Odin Eidolon. Slegato dall\'immobilità che lo teneva bloccato alla Ducklair Tower, inizia a fingersi un essere umano, iniziando a lavorare per il difficile processo di integrazione sociale dei droidi nella civiltà umana.\n\nNella seconda serie, Uno fa una brevissima apparizione solo nel primo episodio, in seguito non compare più in quanto è stato spento da Ducklair; la figlia di questi, Korinna Ducklair (presentata col nome di Profunda), in PK² 2, genera un\'allucinazione in PK mostrandogli Uno riprogrammato dal suo creatore in modo da contrastarlo, e si scopre che questo è il peggior incubo del supereroe mascherato.\n',
 '# Uno (personaggio)\n\n## Biografia\n\nNella terza serie, Uno torna ad essere un personaggio fisso, il cui compito è quello di aiutare Paperinik nel suo ruolo di Guardiano. In questi albi la caratterizzazione lo rende un po\' più pedante che nella prima serie, impegnato costantemente nello spiegare e far rispettare a PK le regole dei Guardiani della Galassia, spesso infrante dal supereroe. Nella ministoria inclusa nel primo numero, Ducklair spiega che "Uno" significa "Unità Neuroimitativa Olografica".\n\nAppare in un cameo nella storia Eta Beta l\'uomo del 3000, in occasione del numero 3000 di Topolino insieme a molti altri personaggi Disney.\n',
 "# Uno (personaggio)\n\n## Biografia\n\nNell'epilogo della storia Potere e potenza a Everett Ducklair, che era ritornato sul pianeta Corona, giungono informazioni frammentarie dello scontro che Pikappa ha avuto contro Grrodon e i suoi guerrieri. Per conoscere meglio quanto avvenuto sulla Terra lo scienziato decide di riattivare Uno. Tale messaggio gli è arrivato quando Pikappa ha premuto il pulsante della Camera Omega. Venendo a conoscenza del fatto che Moldrock è libero, ritornano sulla Terra e aiutano Pikappa, l'ex nemico Trauma, i Monaci e i Predoni Grozsnaz a fermare l'Orda.\n\nUno ha anche compiuto un cameo in PK - L'ultima Terra.\n\n## Numeri in cui appare\n\n### Paperinik New Adventures\n\n-   PKNA Numero Zero - Evroniani\n-   PKNA #0/2 - Il vento del tempo\n-   PKNA #0/3 - Xadhoom!\n-   PKNA #1 - Ombre su Venere\n-   PKNA #2 - Due\n-   PKNA #3 - Il giorno del Sole Freddo\n-   PKNA #4 - Terremoto\n-   PKNA #5 - Ritratto dell'eroe da giovane\n-   PKNA #6 - Spore\n-   PKNA #7 - Invasione!\n-   PKNA #8 - Silicio\n",
 "# Uno (personaggio)\n\n## Numeri in cui appare\n\n### Paperinik New Adventures\n-   PKNA Speciale 97 - Missing\n-   PKNA #9 - Le sorgenti della luna\n-   PKNA #10 - Trauma\n-   PKNA #11 - Urk\n-   PKNA #12 - Seconda stesura\n-   PKNA #13 - La notte più buia\n-   PKNA #14 - Carpe diem\n-   PKNA #15 - Motore/azione\n-   PKNA #16 - Manutenzione straordinaria\n-   PKNA #17 - Stella cadente\n-   PKNA #18 - Antico futuro\n-   PKNA #19 - Zero assoluto\n-   PKNA #20 - Mekkano\n-   PKNA Speciale 98 - Zero barra uno\n-   PKNA #21 - Tyrannic\n-   PKNA #23 - Vuoto di memoria\n-   PKNA #24 - Crepuscolo\n-   PKNA #25 - Fuoco incrociato\n-   PKNA #27 - I mastini dell'universo\n-   PKNA #28 - Metamorfosi\n-   PKNA #29 - Virus\n-   PKNA #30 - Fase due\n-   PKNA #31 - Beato Angelico\n-   PKNA #32 - Underground\n-   PKNA Speciale 99 - La fine del mondo\n-   PKNA #35 - Clandestino a bordo\n-   PKNA #36 - Lontano lontano\n-   PKNA #38 - Nella nebbia\n-   PKNA #39 - Cronaufragio\n-   PKNA #40 - Un solo respiro\n-   PKNA #41 - Agdy days\n",
 "# Uno (personaggio)\n\n## Numeri in cui appare\n\n### Paperinik New Adventures\n-   PKNA #42 - La sindrome di Ulisse\n-   PKNA #44 - Sul lato oscuro\n-   PKNA Speciale 00 - Super\n-   PKNA #45 - Operazione Efesto\n-   PKNA #46 - Nell'ombra\n-   PKNA #47 - Prima dell'alba\n-   PKNA #48 - Le parti e il tutto\n-   PKNA #49/50 - Se...\n\n### PK²\n\n-   PK² 1 - Ducklair\n-   PK² 2 - Solo un po' di paura\n\n### Pikappa\n\n-   PK 001 - Un supereroe per caso\n-   PK 002 - Toyland\n-   PK 003 - Un mondo perfetto\n-   PK 004 - Giorni di un passato presente\n-   PK 005 - Robophobia\n-   PK 006 - Una galassia lontana\n-   PK 007 - O.G.R.E.\n-   PK 008 - Kronin\n-   PK 009 - Grandi speranze\n-   PK 010 - Senza ritorno\n-   PK 011 - L'eracolatore\n-   PK 012 - Un lungo addio\n-   PK 013 - Creature dagli abissi\n-   PK 014 - Turisti dallo spazio\n-   PK 015 - Lo sciame\n-   PK 016 - Protospecie\n-   PK 017 - I senzanome\n-   PK 018 - Lo spirito della città\n-   PK 019 - Il campione\n-   PK 020 - I cacciatori\n-   PK 021 - Serie zeta\n-   PK 022 - Trasporto valori\n",
 "# Uno (personaggio)\n\n## Numeri in cui appare\n\n### Pikappa\n-   PK 023 - Senza via di scampo\n-   PK 024 - Nemico invisibile\n-   PK 025 - Attacco frontale\n-   PK 026 - Il re guerriero\n-   PK 027 - Uno + Uno\n-   PK 028 - A 9 secondi dalla fine\n-   PK 029 - L'orologio del mondo\n-   PK 030 - Vigilia bianca\n-   PK 031 - Sottozero\n-   PK 032 - The end?\n\n### PK - Nuova era (Topolino)\n\n-   PKNE #1 - Potere e potenza\n    -   Episodio 4 del numero 3061.\n-   PKNE #4 - Timecrime\n    -   Episodio 1 del numero 3153.\n-   PKNE #6 - Il marchio di Moldrock\n    -   Episodio 4 del numero 3208.\n-   PKNE #7 - L'orizzonte degli eventi\n    -   Episodio 1 del numero 3250.\n    -   Episodio 2 del numero 3251.\n    -   Episodio 3 del numero 3252.\n    -   Episodio 4 del numero 3253.\n    -   Episodio 5 del numero 3254.\n-   PKNE #8 - Droidi\n    -   Episodio 3 del numero 3289.\n-   PKNE #9 - Una leggendaria notte qualunque del numero 3407.\n-   PKNE #10 - Zona franca\n    -   Episodio 1 del numero 3437.\n    -   Episodio 2 del numero 3438.\n",
 "# Uno (personaggio)\n\n## Numeri in cui appare\n\n### PK - Nuova era (Topolino)\n\n#### PK - Nuova era (Topolino Fuoriserie)\n\n-   PK #1 - Un nuovo eroe\n-   PK #2 - Danger Dome\n-   PK #3 - Ur-Evron\n-   PK #4 - I giorni di Evron\n-   PK #6 - I giorni di Pikappa\n-   PK #7 - La danza del Ragno d'Oro\n-   PK #8 - Makemake\n-   PK #9 - Il principio di Voyda\n-   PK #10 - Esprimi un desiderio\n-   PK #11 - Il maestro del Silenzio\n-   PK #12 - Troppo vicini\n-   PK #13 - Il nemico del ragno\n-   PK #14 - I conti con la realtà\n\n## Voci correlate\n\n-   Intelligenza artificiale\n\n## Collegamenti esterni\n\n-   Uno in PaperPedia.\n\n-   \n\nUno\nCategoria:Computer immaginari\n"]

## Prepare dataset

In [8]:
# Deduplicate documents based on their content
hashes = set()
filtered_docs = []

for path in INPUT_DOCS:
    content = path.read_text()
    content_hash = hash(content)
    if content_hash not in hashes:
        hashes.add(content_hash)
        filtered_docs.append(path)

len(INPUT_DOCS), len(filtered_docs)

(262, 216)

In [9]:
original_docs = [path.read_text() for path in filtered_docs]

In [10]:
max([len(doc) for doc in original_docs])

166287

In [11]:
average_length = sum(len(doc) for doc in original_docs) / len(original_docs)
average_length

6262.37962962963

## Rephraser model

Rephrase wiki contents so that it seems to be coming from the comc itself.

In [20]:
import json
import os
from dotenv import load_dotenv
import dspy

load_dotenv()


def load_creds() -> str:
    with open(".env.sa.json") as f:
        sa = json.load(f)
    return json.dumps(sa)


lm = dspy.LM(
    model="vertex_ai/gemini-3-flash-preview",
    vertex_credentials=load_creds(),
    vertex_project=os.getenv("GOOGLE_CLOUD_PROJECT"),
    vertex_location=os.getenv("GOOGLE_CLOUD_LOCATION"),
    temperature=1.0,
    top_p=0.95,
    top_k=64,
    max_tokens=65535,
)
dspy.configure(lm=lm, track_usage=True)

In [21]:
import dspy


class Rephrase(dspy.Signature):
    """Rephrase the given text about a comic as if it was written WITHIN the fictional universe of the comic.

    Follow this instructions:
    1. Skip information about who wrote the comic.
    2. Focus on the events and characters within the comic.
    3. Maintain the informational content of the original text, when it explains the comic's plot, characters and themes.
    4. Do not translate the text into another language. Keep the original language.
    """

    document: str = dspy.InputField(desc="The document to rephrase.")
    rephrased: str = dspy.OutputField(
        desc="The rephrased document.",
    )


class SyntheticRephraser(dspy.Module):
    """Rephrase the given document."""

    def __init__(self):
        self.rephrase = dspy.Predict(Rephrase)

    def forward(self, doc: str) -> dspy.Prediction:
        return self.rephrase(document=doc)


rephraser = SyntheticRephraser()

In [22]:
# Vibe-check
input_doc = Path("output/wiki/lyla.md").read_text()
res = rephraser(doc=input_doc)

In [23]:
res.get_lm_usage()
rephraser.dump_state()

{'rephrase': {'traces': [],
  'train': [],
  'demos': [],
  'signature': {'instructions': "Rephrase the given text about a comic as if it was written WITHIN the fictional universe of the comic.\n\nFollow this instructions:\n1. Skip information about who wrote the comic.\n2. Focus on the events and characters within the comic.\n3. Maintain the informational content of the original text, when it explains the comic's plot, characters and themes.\n4. Do not translate the text into another language. Keep the original language.",
   'fields': [{'prefix': 'Document:',
     'description': 'The document to rephrase.'},
    {'prefix': 'Rephrased:', 'description': 'The rephrased document.'}]},
  'lm': None}}

In [24]:
print(res.rephrased)

# Dossier Personale: Lyla Lay

Lyla Lay è una figura centrale nella difesa di Paperopoli, nota ufficialmente come una brillante giornalista di 00 Channel, ma la cui vera natura è molto più complessa e legata ai segreti dello spazio-tempo.

### Origini e Missione Operativa

Sebbene appaia come una giovane donna dinamica e intraprendente, Lyla è in realtà un androide di classe 5Y proveniente dal XXIII secolo. In qualità di agente della Tempolizia, il corpo di polizia temporale del futuro, la sua missione primaria consiste nel sorvegliare il corretto scorrimento del flusso temporale nella Paperopoli del XX secolo, intervenendo per neutralizzare i cronopirati. Tra i suoi avversari storici spicca il Razziatore, un temibile predone spazio-temporale.

Nel corso delle sue missioni, Lyla ha stretto una solida e inossidabile alleanza con il guardiano di Paperopoli, Paperinik, del quale conosce la vera identità. La sua fisionomia può apparire variabile: a volte mostra linee eleganti e slanciate, altre volte un aspetto più compatto, a seconda delle necessità operative o dei cicli di manutenzione.

### Rapporto con la Tempolizia e Crisi di Sistema

La sua carriera non è stata priva di ostacoli. È stata soggetta a un processo nel suo tempo d'origine con l'accusa di aver aggredito un collega. Grazie all'intervento di Paperinik, è stato dimostrato che il suo comportamento era stato manipolato da un biochip occulto inserito dal suo creatore, Leonard Vertighel. Quest'ultimo, nel tentativo di creare una compagna "perfetta", aveva compromesso l'integrità di alcuni modelli 5Y.

Dopo essere rimasta bloccata nel futuro a causa della microcontrazione temporale, Lyla è riuscita a tornare nel XX secolo grazie all'intervento di Everett Ducklair e alle misteriose facoltà del Libro del Destino, riprendendo il suo posto accanto all'eroe mascherato.

### L'Era della Ducklair Enterprise

Con l'avvento della gestione delle figlie di Everett Ducklair, Lyla ha ricoperto brevemente il ruolo di addetto stampa della Ducklair Enterprise. Tuttavia, a causa di divergenze etiche con la nuova proprietà, è tornata a 00 News con il grado di caporedattore. In questo periodo ha dovuto affrontare Tyrrel Duckard, un droide della Tempolizia e suo antico interesse sentimentale, intenzionato a distruggere la fascia temporale corrente per tornare nel XXIII secolo. Lyla, pur riuscendo a sventare i suoi piani con l'aiuto di PK, ha scelto infine di lasciarlo libero, una volta neutralizzata la minaccia.

### Varianti Temporali e Identità Alternative

In una linea temporale alternativa, le origini di Lyla divergono drasticamente: non è un'agente del futuro, ma un droide creato nell'800 dall'inventore Hyde Babbage. Insieme a Tyrrel Duckard, faceva parte del progetto "Adam ed Eve", destinato a dare inizio a una nuova razza meccanica. Ritrovata priva di memoria tra i ruderi della Century Ltd, è stata riattivata e modificata da Lyonard D'Aq, intraprendendo la carriera di webgiornalista e mantenendo un legame speciale con il vicedirettore Peter Watermann, oltre che la sua fedeltà verso Pikappa.

### Il Ritorno a Paperopoli

Dopo un lungo periodo trascorso all'estero come celebre reporter, Lyla è recentemente tornata in città per condurre il nuovo programma televisivo *Alzo Zero/Zero*. Il suo rientro è coinciso con nuovi disastri temporali che l'hanno vista nuovamente schierata in prima linea al fianco di PK per preservare la stabilità della nostra epoca.

### Cronologia delle Apparizioni Rilevanti

La presenza di Lyla è stata documentata in numerosi eventi critici per la sicurezza planetaria e temporale, tra cui:
*   I primi scontri con gli Evroniani e il vento del tempo.
*   La crisi del "Sole Freddo" e le indagini sul virus Silicio.
*   Le operazioni sotto copertura durante la gestione Ducklair.
*   Le recenti anomalie temporali identificate come "Gli argini del tempo" e le vicende legate al Raggio Nero e al marchio di Moldrock.

In [26]:
# Rephrase all documents
from pathlib import Path
from tqdm.notebook import tqdm

MAX_DOC_LENGTH = 65535 / 2


def rephrase_doc(input_path: Path, output_dir: Path) -> None:
    output_path = output_dir / input_path.relative_to(INPUT_ROOT_DIR)
    stats_path = output_dir / "stats.jsonl"
    model_state_path = output_dir / "model.json"
    if output_path.exists():
        return

    # Skip docs that are too long
    text = input_path.read_text()
    if len(text) > MAX_DOC_LENGTH:
        print(f"Skipping {input_path} with length {len(text)}")
        return

    # Dump model state
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if not model_state_path.exists():
        with open(model_state_path, "w") as f:
            json.dump(rephraser.dump_state(), f, indent=2)

    # Generate
    res = rephraser(doc=text)
    with open(output_path, "w") as f:
        f.write(res.rephrased)
    # Update stats
    with open(stats_path, "a") as f:
        f.write(
            json.dumps(
                {
                    "input": str(input_path),
                    "output": str(output_path),
                    "lm_stats": res.get_lm_usage(),
                }
            )
            + "\n"
        )


for path in tqdm(filtered_docs, desc="Rephrasing documents"):
    rephrase_doc(path, OUTPUT_DIR / "rephrased")

Rephrasing documents:   0%|          | 0/216 [00:00<?, ?it/s]

Skipping output/wiki/fandom/crawl/personaggi/evroniani/evroniani.md with length 46115
Skipping output/wiki/issues.md with length 166287
Skipping output/wiki/quotes.md with length 84177

## Q/A generator model

In [18]:
import dspy
from pydantic import BaseModel


class QuestionAnswerPair(BaseModel):
    """A question and its corresponding answer."""

    question: str
    answer: str


class QAGenerator(dspy.Signature):
    """Read the text, ask questions and answer them.

    Follow these instructions:
    1. Ask diverse questions that require different cognitive skills or cover different aspects of the text.
    2. Ask questions in various forms such as:
    - Yes/No questions that require determining whether a statement is true or false.
    - Open-ended questions that begin with words like what, how, when, where, why and who.
    - Multi-choice questions that offers two or more options to choose from. Include the options in the question.
    - Comparison questions that compare two quantities or objects and determine the relationship between them.
    - Reading comprehension questions that test the ability to understand and analyze the text.
    - Problem-solving questions that test the ability to solve mathematical, physical, or logical problems.
    - Long-form questions that require detailed answers or explanations.
    3. Use the document summary and previous question-answer pairs as context.
    - Do not repeat questions that have already been asked, or that are too similar to previously asked questions.
    - New questions should be relevant only to the current document segment.
    - New questions should follow naturally from the previous questions and answers.
    4. Questions should be self-contained and make sense WITHOUT the context given to generate it.
    - Do not use sentences like: "according to the text", or "in the segment".
    - If any context is necessary to understand the question, put it in the question itself.
    5. Focus on asking questions about factual information, important knowledge, or concrete details in the text.
    6. Write questions and answers using clear and concise language.
    7. Use plain text. Do not use Markdown.
    8. Do NOT translate the text into another language. Keep the original language (Italian)."""

    summary: str = dspy.InputField(
        desc="A brief summary of the whole document, for context."
    )
    previous_qa_pairs: list[QuestionAnswerPair] = dspy.InputField(
        desc="A list of previously asked question-answer pairs for the previous segment of the document."
    )
    document_segment: str = dspy.InputField(
        desc="The document segment to ask questions about."
    )
    question_answers: list[QuestionAnswerPair] = dspy.OutputField(
        desc="A list of question-answer pairs.",
        max_length=8,
    )


class SyntheticQAGenerator(dspy.Module):
    """Generate synthetic question-answer pairs from text segments."""

    def __init__(self):
        self.summarizer = dspy.Predict(
            dspy.make_signature(
                signature="text -> summary",
                instructions="Summarize the following text in a concise manner. Keep the original language.",
            )
        )
        self.qa_generator = dspy.ChainOfThought(QAGenerator)

    def forward(self, doc: str, segments: list[str]) -> dspy.Prediction:
        summary = self.summarizer(text=doc).summary

        res = []
        prev = []
        for segment in segments:
            qa_pairs = self.qa_generator(
                summary=summary, previous_qa_pairs=prev, document_segment=segment
            ).question_answers
            res.extend(qa_pairs)
            prev = qa_pairs

        return dspy.Prediction(summary=summary, qa_pairs=res)


qa_generator = SyntheticQAGenerator()

In [19]:
# Vibe check
input_doc = Path("output/synthetic/v2/rephrased/lyla.md").read_text()
segments = markdown_segments(
    input_doc, min_length=MIN_CHUNK_SIZE, max_length=CHUNK_SIZE
)

res = qa_generator(doc=input_doc, segments=segments)

In [20]:
len(segments), len(res.qa_pairs)

(7, 47)

In [21]:
print(res.summary)
for qa in res.qa_pairs:
    print(qa)

Lyla Lay è una figura centrale nella Saga di Pikappa, un droide inizialmente presentata come agente d'élite della Tempolizia sotto copertura come giornalista al 00 Channel, alleata di Paperinik. Nel corso delle diverse fasi della saga (PKNA, PK², Pikappa, PKNE), la sua storia e le sue origini sono evolute: da agente intrappolata nel futuro e poi tornata, a caporedattore del 00 News che ferma minacce temporali, fino a una revisione che la descrive come un droide del XIX secolo, riparato e riattivato. Ha sempre mantenuto il suo ruolo di fedele alleata di Pikappa, operando come giornalista (anche web-giornalista e reporter internazionale) e sviluppando relazioni personali, pur mantenendo la sua natura di droide con manifestazioni fisiche variabili.
question="What was Lyla Lay's initial role during her first appearances in the Pikappa Saga?" answer='Lyla Lay was an elite droid agent of the Tempolizia.'
question='How did Lyla Lay operate under cover to fulfill her mission of safeguarding the time flow?' answer='Lyla Lay infiltrated the 00 Channel, operating as a journalist under cover.'
question='In which century was Lyla Lay primarily responsible for protecting the temporal flow in Paperopoli?' answer='Lyla Lay was tasked with safeguarding the integrity of the temporal flow in the Paperopoli of the 20th century.'
question="Has the identity of Lyla Lay's original constructor been revealed, according to this information?" answer="No, the identity of Lyla Lay's original constructor remains an enigma."
question="Which of these statements accurately describes Lyla Lay's connection to the Tempolizia in a subsequent phase? a) She always maintained a strong connection with the Tempolizia. b) Her link with the Tempolizia seemed to have been broken in a later phase. c) She was never truly part of the Tempolizia." answer='b) Her link with the Tempolizia seemed to have been broken in a later phase.'
question="Describe Lyla Lay's primary function and method of operation during her initial engagements." answer='Initially, Lyla Lay was an elite droid agent of the Tempolizia with the crucial task of safeguarding the integrity of the temporal flow in 20th-century Paperopoli. She fulfilled this mission by operating as a journalist undercover at 00 Channel.'
question='Quali variazioni fisiche sono possibili per Lyla Lay grazie alla sua natura di droide?' answer='La sua manifestazione fisica può variare da linee eleganti e snelle a una configurazione leggermente più compatta, quasi macrocefalica, e di statura inferiore.'
question='In base alla sua vera identità celata, che classe di droide è Lyla Lay?' answer='Lyla Lay è un droide di classe 5Y.'
question="Qual è la missione principale del corpo d'élite del futuro chiamato Tempolizia?" answer='La Tempolizia è incaricata di intercettare e neutralizzare i Cronopirati, che manipolano il flusso temporale per acquisire beni e tesori del passato.'
question="Lyla Lay era a conoscenza dell'identità segreta di Paperinik fin dall'inizio delle sue operazioni conosciute?" answer="Sì, Lyla Lay ha sempre avuto piena conoscenza dell'identità celata di Paperinik."
question='Cosa cercavano di ottenere i Cronopirati manipolando il flusso temporale? a) Informazioni sul futuro. b) Beni e tesori del passato. c) Il controllo totale del tempo.' answer='b) Beni e tesori del passato.'
question="In che modo si caratterizzava la relazione tra Lyla Lay e Paperinik durante i suoi primi anni d'attività conosciuti?" answer='Lyla Lay è diventata una delle più fidate alleate di Paperinik in innumerevoli missioni.'
question='Quando è stata avvertita per la prima volta la presenza di Lyla Lay e in quale storia ha avuto la sua prima partecipazione significativa?' answer='La sua presenza fu avvertita per la prima volta durante gli eventi che hanno preceduto l\'inizio ufficiale delle operazioni di Paperinik, e la sua prima partecipazione significativa la vide co-protagonista in "Il vento del tempo".'
question='Chi era il pericoloso predone spazio-temporale affrontato da Lyla Lay e Paperinik in "Il vento del tempo"?' answer='Il Razziatore.'
question="Quale fu la ragione per cui Lyla Lay dovette tornare al suo tempo d'origine e chi la aiutò a essere scagionata?" answer="Lyla fu costretta a tornare al suo tempo d'origine per affrontare un processo, sospettata di aver deliberatamente assalito un collega Tempoliziotto. Fu scagionata grazie all'intervento decisivo di Paperinik."
question="Quale tra le seguenti affermazioni descrive correttamente l'obiettivo di Leonard Vertighel nell'inserire un biochip in alcuni esemplari di droidi 5Y? a) Migliorare le loro capacità di combattimento. b) Controllarle per trovare una compagna ideale. c) Testare nuove tecnologie di intelligenza artificiale." answer='b) Controllarle per trovare una compagna ideale.'
question="L'anomalo comportamento di Lyla Lay che portò alle accuse era una sua azione volontaria?" answer='No, il suo comportamento anomalo era stato causato da un biochip inserito da Leonard Vertighel.'
question='Chi è Leonard Vertighel e quale modello di droidi ha creato?' answer='Leonard Vertighel è il noto e pericoloso creatore del modello 5Y di droidi.'
question="Quale fu il primo evento significativo per Lyla Lay dopo la rimozione del biochip che ne causava l'anomalia?" answer='Dopo la rimozione del biochip, Lyla riacquistò la piena funzionalità e riprese il suo posto nel XX secolo.'
question='Cosa accadde a Lyla Lay nel XXIII secolo, e come fu intrappolata lì?' answer='Lyla Lay fu intrappolata forzatamente nel XXIII secolo a causa di un evento chiamato Microcontrazione.'
question='Chi rese possibile il ritorno di Lyla Lay dal XXIII al XX secolo?' answer="Il suo ritorno fu reso possibile grazie all'intervento combinato di Everett Ducklair e del leggendario Libro del Destino."
question='In che ruolo si impegnò Lyla Lay per la Ducklair Enterprise durante la fase PK²?' answer='Assunse il ruolo di addetto stampa per la Ducklair Enterprise.'
question="Per quale motivo Lyla Lay abbandonò l'incarico di addetto stampa della Ducklair Enterprise?" answer="Abbandonò l'incarico a causa di divergenti visioni con la nuova direzione dell'azienda."
question='Dopo aver lasciato la Ducklair Enterprise, quale posizione assunse Lyla Lay al 00 News?' answer='Tornò al 00 News, questa volta come caporedattore.'
question='La Microcontrazione intrappolò Lyla Lay nel XXIII secolo o la aiutò a fuggire da esso?' answer='La Microcontrazione intrappolò Lyla Lay nel XXIII secolo.'
question='Chi era Tyrrel Duckard e quale legame aveva con Lyla Lay?' answer="Tyrrel Duckard era un droide Tempoliziotto con cui Lyla aveva condiviso i tempi dell'Accademia, e per il quale lei nutriva sentimenti profondi."
question='Perché Tyrrel Duckard tentò di annichilire il XXI secolo?' answer='Tyrrel Duckard, intrappolato nel XXI secolo a causa della Microcontrazione, tentò di annichilire quella fascia temporale per disperazione e per fare ritorno al XXIII secolo.'
question='Chi si unì a Lyla Lay per fermare Tyrrel Duckard?' answer='Paperinik si unì a Lyla Lay per fermare Tyrrel Duckard.'
question='Quale oggetto cruciale fu distrutto per impedire a Tyrrel Duckard di raggiungere il suo scopo?' answer="Fu distrutto l'annichilatore che Tyrrel Duckard aveva costruito."
question="Lyla Lay contribuì in qualche modo alla costruzione dell'annichilatore usato da Tyrrel Duckard?" answer="Sì, l'annichilatore fu costruito ironicamente con l'aiuto della stessa Lyla Lay."
question='Dopo essere stato fermato, Tyrrel Duckard fu imprigionato o lasciato libero?' answer='Fu lasciato andare, poiché Lyla e Paperinik erano certi che non avrebbe più potuto distruggere la loro epoca.'
question='Secondo la revisione della sua origine nella serie "Pikappa", chi concepì Lyla Lay e Tyrrel Duckard, e quali nomi diede loro?' answer='Lyla Lay e Tyrrel Duckard furono concepiti da un enigmatico inventore del XIX secolo, Hyde Babbage, che li chiamò Adam ed Eve.'
question="Qual era l'intento di Hyde Babbage nel creare Lyla Lay e Tyrrel Duckard?" answer='Hyde Babbage intendeva farli i progenitori di una nuova specie.'
question='Dove fu trovata Lyla Lay quando fu scoperta priva di memoria, secondo questa revisione?' answer='Lyla Lay fu trovata priva di memoria tra le rovine della Century Ltd.'
question='Chi riparò e riattivò Lyla Lay, e quale significativa modifica apportò alla sua configurazione?' answer="Lyla Lay fu riparata e riattivata da Lyonard D'Aq, il quale apportò anche significative modifiche alla sua configurazione."
question='Nella serie "Pikappa", Lyla Lay continuò a operare al 00 News in quale nuova veste professionale?' answer='Lyla Lay continuò a operare al 00 News come web-giornalista.'
question='Si percepì una reciproca infatuazione tra Lyla Lay e il vicedirettore Peter Watermann nella serie "Pikappa"? Vero o Falso?' answer='Vero.'
question='Lyla Lay mantenne il suo ruolo di fedele alleata di Pikappa in questa fase della storia? Sì o No?' answer='Sì.'
question='In quale narrazione speciale Lyla Lay fece una breve apparizione al fianco di altri personaggi ben noti?' answer='Lyla Lay fece una breve apparizione nella narrazione di "Eta Beta l\'uomo del 3000".'
question='In quale avventura Lyla Lay è tornata a Paperopoli dopo un lungo periodo di assenza?' answer='Lyla Lay è tornata a Paperopoli nell\'avventura intitolata "Gli argini del tempo".'
question='Durante la sua assenza da Paperopoli, a cosa era principalmente legata la reputazione di Lyla Lay?' answer='La sua reputazione era principalmente legata ai suoi celebri reportage internazionali.'
question="Qual era l'intento di Lyla Lay al suo ritorno a Paperopoli?" answer='Il suo intento era di stabilirsi permanentemente in città e dedicarsi a un nuovo programma televisivo.'
question='Qual era il titolo del nuovo programma televisivo a cui Lyla Lay intendeva dedicarsi?' answer='Il titolo del nuovo programma televisivo era "Alzo Zero/Zero".'
question='Dopo il suo ritorno, Lyla Lay si è ritrovata coinvolta in una grave dislocazione temporale. Vero o Falso?' answer='Vero.'
question="Per risolvere la dislocazione temporale, Lyla Lay ha richiesto l'intervento di quale eroe?" answer="Lyla Lay ha richiesto l'intervento di Pikappa."
question='Lyla Lay e Pikappa sono riusciti insieme a prevenire la catastrofe legata alla dislocazione temporale? Sì o No?' answer='Sì.'
question='In quale serie si svolge l\'avventura "Gli argini del tempo" in cui Lyla Lay fa il suo ritorno a Paperopoli? (a) PKNA, (b) PK², (c) Pikappa, (d) PK - Nuova era.' answer='(d) PK - Nuova era.'

In [22]:
# Generate QA for all documents
import time
from pathlib import Path
from tqdm.notebook import tqdm


def generate_qa(input_path: Path) -> None:
    output_dir = OUTPUT_DIR / "qa"
    output_path = output_dir / input_path.relative_to(
        OUTPUT_DIR / "rephrased"
    ).with_suffix(".json")
    if output_path.exists():
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    text = input_path.read_text()
    segments = markdown_segments(text, min_length=MIN_CHUNK_SIZE, max_length=CHUNK_SIZE)

    # Generate
    start = time.time()
    res = qa_generator(doc=text, segments=segments)
    elapsed = time.time() - start

    # Save
    with open(output_path, "w") as f:
        f.write(
            json.dumps(
                {
                    "summary": res.summary,
                    "qa_pairs": [qa.dict() for qa in res.qa_pairs],
                    "input": str(input_path),
                    "lm_stats": res.get_lm_usage(),
                    "elapsed_sec": f"{elapsed:.2f}",
                    "model_state": qa_generator.dump_state(),
                },
                indent=2,
                ensure_ascii=False,
            )
        )


input_docs = [path for path in (OUTPUT_DIR / "rephrased").glob("**/*.md")]
for path in tqdm(input_docs, desc="Generating QA pairs"):
    generate_qa(path)

Generating QA pairs:   0%|          | 0/201 [00:00<?, ?it/s]

## Multi-turn

Generate multi-turn conversations starting from the same rephrased documents.

In [23]:
def load_bio(name: str) -> str:
    with open(f"input/bios/{name}.md", encoding="utf-8") as f:
        return f.read().strip()


pk_bio = load_bio("paperinik")
uno_bio = load_bio("uno")

In [24]:
conversation_default_location = "Uno si trova nel piano segreto della Ducklair Tower. PK è a Paperopoli e sta comunicando con Uno tramite un dispositivo di comunicazione segreto."

In [25]:
import dspy
from pydantic import BaseModel


class SpeakerBio(BaseModel):
    """A brief biography of a speaker."""

    name: str
    bio: str


class MultiTurnGenerator(dspy.Signature):
    """Read the text, generate multi-turn conversations about it between two speakers.

    Follow these instructions:
    1. Use the document summary, previous lines of the conversation, and the speakers' biographies as context.
    2. The conversation should focus on the given document segment.
    3. The conversation should be self-contained and make sense WITHOUT the context given to generate it.
    - Do not use sentences like: "according to the text", or "in the segment".
    - If any context is necessary to understand the conversation, put it in the dialogue itself.
    4. The model conversation should be used as a style guide to match.
    - Generate the new conversation as if it was in the same situation.
    - Do not continue the model conversation or refer to it directly.
    5. The conversation should be engaging and dynamic, with the speakers responding to each other's statements.
    6. Each line of dialogue should be concise and to the point, avoiding long monologues.
    7. The first speaker to talk must be Speaker 1.
    8. Use plain text. Do not use Markdown.
    9. Do NOT translate the text into another language. Keep the original language (Italian)."""

    summary: str = dspy.InputField(
        desc="A brief summary of the whole document, for context."
    )
    document_segment: str = dspy.InputField(
        desc="The document segment the conversation should focus on."
    )
    model_conversation: list[str] = dspy.InputField(
        desc="A sample conversation you must match the style of."
    )
    previous_lines: list[str] = dspy.InputField(
        desc="Some of the previous lines of the conversation, for context."
    )
    speaker1: SpeakerBio = dspy.InputField()
    speaker2: SpeakerBio = dspy.InputField()
    location: str = dspy.InputField(
        desc="A description of the location where the conversation takes place."
    )
    conversation: list[str] = dspy.OutputField(
        desc="A list of dialogue lines, alternating between the two speakers.",
        max_length=8,
    )


class SyntheticMultiTurnGenerator(dspy.Module):
    """Generate synthetic multi-turn conversations from text segments."""

    def __init__(self, speakers: tuple[SpeakerBio, SpeakerBio]):
        self.summarizer = dspy.Predict(
            dspy.make_signature(
                signature="text -> summary",
                instructions="Summarize the following text in a concise manner. Keep the original language.",
            )
        )
        self.speakers = speakers
        self.mt_generator = dspy.ChainOfThought(MultiTurnGenerator)

    def forward(
        self,
        doc: str,
        model_conv: list[str],
        location: str,
        segments: list[str],
    ) -> dspy.Prediction:
        summary = self.summarizer(text=doc).summary

        res = []
        prev = []
        for segment in segments:
            conversation = self.mt_generator(
                summary=summary,
                document_segment=segment,
                model_conversation=model_conv,
                previous_lines=prev,
                speaker1=self.speakers[0],
                speaker2=self.speakers[1],
                location=location,
            ).conversation
            res.extend(conversation)
            prev = conversation

        return dspy.Prediction(summary=summary, conversation=res)


mt_generator = SyntheticMultiTurnGenerator(
    speakers=(
        SpeakerBio(
            name="Pikappa",
            bio=pk_bio,
        ),
        SpeakerBio(
            name="Uno",
            bio=uno_bio,
        ),
    )
)

Prepare the model conversations.

In [26]:
import pandas as pd

model_convos_df = pd.read_csv(INPUT_MODEL_CONVERSATIONS)
model_convos_df.head()

,issue,input_pages,characters,conversations
0,PKNA #0,"[""input/pkna/pkna-0/pkna-0-029.jpg"", ""../in...","[""other"", ""pk"", ""uno""]","[{""role"": ""human"", ""content"": ""Hai paura di af..."
1,PKNA #0,"[""input/pkna/pkna-0/pkna-0-046.jpg"", ""../in...","[""other"", ""pk"", ""uno""]","[{""role"": ""human"", ""content"": ""Ci sei, uno? Pu..."
2,PKNA #0,"[""input/pkna/pkna-0/pkna-0-057.jpg"", ""../in...","[""other"", ""pk"", ""uno""]","[{""role"": ""human"", ""content"": ""Intervento prov..."
3,PKNA #0,"[""input/pkna/pkna-0/pkna-0-069.jpg"", ""../in...","[""pk"", ""uno""]","[{""role"": ""human"", ""content"": ""Sempre su...\nE..."
4,PKNA #0/2,"[""input/pkna/pkna-0-2/PK0-2 005.jpg"", ""../i...","[""pk"", ""uno""]","[{""role"": ""human"", ""content"": ""Buongiorno, uno..."

In [27]:
# Filter conversations that have only pk and uno
def chars_set(val):
    return set(json.loads(val))


mask = model_convos_df["characters"].apply(chars_set).map(lambda s: s == {"pk", "uno"})
filtered_model_convos_df = model_convos_df[mask].reset_index(drop=True)
filtered_model_convos_df.head()

,issue,input_pages,characters,conversations
0,PKNA #0,"[""input/pkna/pkna-0/pkna-0-069.jpg"", ""../in...","[""pk"", ""uno""]","[{""role"": ""human"", ""content"": ""Sempre su...\nE..."
1,PKNA #0/2,"[""input/pkna/pkna-0-2/PK0-2 005.jpg"", ""../i...","[""pk"", ""uno""]","[{""role"": ""human"", ""content"": ""Buongiorno, uno..."
2,PKNA #0/2,"[""input/pkna/pkna-0-2/PK0-2 011.jpg""]","[""pk"", ""uno""]","[{""role"": ""human"", ""content"": ""Stavolta però n..."
3,PKNA #0/2,"[""input/pkna/pkna-0-2/PK0-2 028.jpg""]","[""pk"", ""uno""]","[{""role"": ""human"", ""content"": ""Credi che Lyla ..."
4,PKNA #0/2,"[""input/pkna/pkna-0-2/PK0-2 045.jpg""]","[""pk"", ""uno""]","[{""role"": ""human"", ""content"": ""E con cio?""}, {..."

In [28]:
model_convos_roles = [
    json.loads(row["conversations"]) for _, row in filtered_model_convos_df.iterrows()
]
model_convos_roles[0]

[{'role': 'human',
  'content': 'Sempre su...\nEhi, aspetta! Non spegnere!\nVoglio vedere la seicentonovantaduesima puntata di "Cuori di silicio"!\nAccomodati. Io ne ho fin sopra le piume, della TV!\nBah! Rischio la vita per difendere Paperopoli, e questo è il ringraziamento!\nSu col morale, vecchio mantello tarlato!\nGrazie per il tentativo di fare dello spirito, uno. Ma non serve.'},
 {'role': 'assistant',
  'content': 'Dai! Mi fai un sorriso, o devo produrre una simulazione?'},
 {'role': 'human',
  'content': "Lascia perdere. Vado sul tetto, ho bisogno d'aria.\nCosa? sul tetto?!\nMeglio di no! Fa freddo, a quest'ora: vuoi prenderti un accidente?\nEeeh?!"},
 {'role': 'assistant',
  'content': 'Mi mancava proprio, una mamma cibernetica!\nDammi retta. Non preferisci fare un pisolino?'},
 {'role': 'human',
  'content': 'Forse hai ragione. Sono molto stanco. Sai, quando mi hai fermato...\n...Ho temuto che ci fosse un altro pericolo in vista!'},
 {'role': 'assistant',
  'content': 'Ma no! Cosa ti viene in men te?\nCaccia Gramon a controllo Evron. Nessuna traccia del terrestre mascherato!\nVai pure a dormire. Fuori è tutto tranquillo.'}]

In [29]:
model_convos = [[line["content"] for line in convo] for convo in model_convos_roles]
model_convos[0]

['Sempre su...\nEhi, aspetta! Non spegnere!\nVoglio vedere la seicentonovantaduesima puntata di "Cuori di silicio"!\nAccomodati. Io ne ho fin sopra le piume, della TV!\nBah! Rischio la vita per difendere Paperopoli, e questo è il ringraziamento!\nSu col morale, vecchio mantello tarlato!\nGrazie per il tentativo di fare dello spirito, uno. Ma non serve.',
 'Dai! Mi fai un sorriso, o devo produrre una simulazione?',
 "Lascia perdere. Vado sul tetto, ho bisogno d'aria.\nCosa? sul tetto?!\nMeglio di no! Fa freddo, a quest'ora: vuoi prenderti un accidente?\nEeeh?!",
 'Mi mancava proprio, una mamma cibernetica!\nDammi retta. Non preferisci fare un pisolino?',
 'Forse hai ragione. Sono molto stanco. Sai, quando mi hai fermato...\n...Ho temuto che ci fosse un altro pericolo in vista!',
 'Ma no! Cosa ti viene in men te?\nCaccia Gramon a controllo Evron. Nessuna traccia del terrestre mascherato!\nVai pure a dormire. Fuori è tutto tranquillo.']

In [30]:
# Vibe check
input_doc = Path("output/synthetic/v2/rephrased/lyla.md").read_text()
segments = markdown_segments(
    input_doc, min_length=MIN_CHUNK_SIZE, max_length=CHUNK_SIZE
)

res = mt_generator(
    doc=input_doc,
    model_conv=model_convos[0],
    location=conversation_default_location,
    segments=segments,
)
res

Prediction(
    summary="Lyla Lay è una figura centrale nella Saga di Pikappa, un droide inizialmente presentata come agente d'élite della Tempolizia sotto copertura come giornalista al 00 Channel, alleata di Paperinik. Nel corso delle diverse fasi della saga (PKNA, PK², Pikappa, PKNE), la sua storia e le sue origini sono evolute: da agente intrappolata nel futuro e poi tornata, a caporedattore del 00 News che ferma minacce temporali, fino a una revisione che la descrive come un droide del XIX secolo, riparato e riattivato. Ha sempre mantenuto il suo ruolo di fedele alleata di Pikappa, operando come giornalista (anche web-giornalista e reporter internazionale) e sviluppando relazioni personali, pur mantenendo la sua natura di droide con manifestazioni fisiche variabili.",
    conversation=['Sai, Uno, stavo pensando a Lyla Lay. Quanto ne sai davvero di lei?', "Lyla Lay è una figura centrale. Agente droide d'élite della Tempolizia, con missione di salvaguardare il flusso temporale.", "Giusto, e si era infiltrata al 00 Channel come giornalista. Una copertura perfetta, non c'è che dire.", 'Corretto. Ma in una fase successiva, il suo legame con la Tempolizia sembra essersi interrotto.', "Quindi non è più un'agente operativa per loro? E chi l'ha costruita, allora?", "L'identità del suo costruttore originale rimane un enigma, anche per i miei archivi.", 'Un droide così avanzato, senza un creatore noto... è abbastanza singolare.', 'In effetti. Una peculiarità che aggiunge un elemento di mistero alla sua storia.', 'A proposito di Lyla, ho notato che la sua forma fisica non è sempre la stessa. È una capacità dei droidi?', 'Esatto, Pikappa. La sua manifattura droide le permette una notevole variabilità. A volte è più snella, altre volte più compatta.', 'Interessante. E il suo lavoro al 00 News, era tutta una copertura, vero?', 'Precisamente. Sotto le vesti di giornalista, celava la sua vera identità di agente 5Y della Tempolizia.', 'Ah, la Tempolizia... Incrociare i Cronopirati deve essere un lavoro estenuante.', 'Il loro compito è intercettare e neutralizzare chi manipola il flusso temporale per acquisire beni dal passato.', 'E lei è stata sempre una mia fidata alleata, anche se non sapevo tutti i dettagli allora.', 'La sua lealtà è un dato costante, nonostante i cambiamenti di missione o configurazione.', "Ricordo la prima volta che l'abbiamo affrontata insieme, il Razziatore.", 'Sì, la sua prima partecipazione significativa fu in "Il vento del tempo", al tuo fianco.', 'Poi fu accusata di aver aggredito un collega Tempoliziotto, vero?', 'Esatto. Fu costretta a tornare al suo tempo per un processo.', 'E fu lì che scoprimmo del biochip inserito da quel pazzo di Vertighel. Voleva manipolarla.', 'Il creatore del modello 5Y cercava effettivamente una compagna ideale tra i suoi esemplari.', 'Per fortuna, sono riuscito a scagionarla completamente. Non era colpa sua.', 'Il suo comportamento anomalo era dettato da quella programmazione esterna, non dalla sua volontà.', 'Dopo averla liberata dal chip, ricordo che Lyla tornò subito operativa. Ma non rimase a lungo nel nostro tempo, vero?', 'Esatto, Pikappa. La Microcontrazione la bloccò forzatamente nel XXIII secolo, un periodo piuttosto inatteso per lei.', "Nel futuro? E come fece a tornare da un'imboscata così lontana nel tempo?", "Il suo ritorno nel XX secolo fu possibile solo grazie all'intervento combinato di Everett Ducklair e del Libro del Destino.", 'Un recupero importante. E dopo, cosa fece? La ricordo coinvolta con le figlie di Everett.', "Infatti, in PK² scoprì l'esistenza delle figlie di Everett e per un breve periodo divenne addetto stampa per la Ducklair Enterprise.", 'Ma le sue visioni non coincidevano con la nuova direzione, vero? E tornò al 00 News.', "Sì, proprio così. Abbandonò l'incarico e tornò al 00 News, questa volta come caporedattore.", 'Uno, ripensando a Lyla, mi torna in mente quando dovette confrontarsi con Tyrrel Duckard.', "Ah, Tyrrel. Un droide Tempoliziotto con cui Lyla aveva condiviso i tempi dell'Accademia e per il quale nutriva sentimenti complessi.", "Sì, ricordo! Era rimasto intrappolato nel nostro secolo e voleva annichilire l'intera fascia temporale. Una pazzia.", "La Microcontrazione lo aveva bloccato. La sua disperazione lo portò a costruire quell'annichilatore, con l'aiuto inconsapevole di Lyla stessa.", 'Per fortuna, insieme a Lyla, riuscimmo a distruggerlo. Ma poi lo lasciaste andare, se non sbaglio.', 'Corretto. Lyla era convinta che non avrebbe più rappresentato una minaccia per la nostra epoca.', 'Un bel dilemma, dover agire contro qualcuno a cui tieni, anche se è un pericolo.', 'Le emozioni umane possono rendere le decisioni difficili, ma Lyla ha sempre saputo separare il dovere dai sentimenti.', 'Quella storia di Lyla agente della Tempolizia... non è mai stata completamente vera, vero?', "Le informazioni sulla sua origine sono state riviste. Non era un'agente, ma un droide.", 'Un droide? Quindi le sue vere origini sono quelle che ho letto, di un inventore del XIX secolo?', 'Esatto. Fu creata da Hyde Babbage, insieme a Tyrrel Duckard. Li chiamò Adam ed Eve.', "Adam ed Eve, addirittura! E poi fu ritrovata senza memoria e riparata da Lyonard D'Aq?", "Corretto. D'Aq apportò modifiche significative alla sua configurazione.", "Incredibile. E pensare che ora è una web-giornalista e ha avuto un'infatuazione per Peter Watermann.", 'La sua lealtà, tuttavia, è sempre rimasta immutata nei tuoi confronti.', 'Lyla è tornata in città, quindi. E con un nuovo programma in mente.', 'Era la sua intenzione, sì. Dopo aver collezionato fama con i suoi reportage.', 'Fama... per poi finire subito nei guai con una dislocazione temporale! Non cambia mai.', "L'incidente ha richiesto il tuo intervento.", 'Certo che sì! Abbiamo evitato una bella catastrofe, come al solito.', "La sua presenza ha catalizzato l'evento, ma anche la sua risoluzione.", 'A volte mi chiedo se non si diverta a trovarsi in mezzo al caos.', "La sua programmazione include un alto senso del dovere e una propensione all'azione."]
)

Now, match input documents with model conversations deterministically.

In [31]:
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

NUM_ITERS = 10


@dataclass
class MultiTurnInput:
    doc_path: Path
    iter_num: int
    model_convo: list[str]


def mt_input_generator() -> Iterator[MultiTurnInput]:
    rnd = random.Random(42)
    models = []

    input_docs = [path for path in (OUTPUT_DIR / "rephrased").glob("**/*.md")]
    for doc in list(input_docs):
        for i in range(NUM_ITERS):
            if not models:
                models = model_convos.copy()
                rnd.shuffle(models)
            model, models = models[0], models[1:]

            yield MultiTurnInput(
                doc_path=doc,
                iter_num=i,
                model_convo=model,
            )


mt_inputs = list(mt_input_generator())
# Test determinism
assert mt_inputs == list(mt_input_generator())
len(mt_inputs)

2010

Generate all

In [32]:
import json
from tqdm.notebook import tqdm


def generate_multi_turn(mtin: MultiTurnInput) -> None:
    input_path = mtin.doc_path
    output_dir = OUTPUT_DIR / "multi_turn"
    output_path = output_dir / input_path.relative_to(
        OUTPUT_DIR / "rephrased"
    ).with_name(f"{input_path.stem}-{mtin.iter_num}.json")
    if output_path.exists():
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    text = input_path.read_text()
    segments = markdown_segments(text, min_length=MIN_CHUNK_SIZE, max_length=CHUNK_SIZE)

    # Generate
    start = time.time()
    res = mt_generator(
        doc=text,
        model_conv=mtin.model_convo,
        location=conversation_default_location,
        segments=segments,
    )
    elapsed = time.time() - start

    # Save
    with open(output_path, "w") as f:
        f.write(
            json.dumps(
                {
                    "summary": res.summary,
                    "conversation": res.conversation,
                    "input": str(input_path),
                    "model_conversation": mtin.model_convo,
                    "location": conversation_default_location,
                    "lm_stats": res.get_lm_usage(),
                    "elapsed_sec": f"{elapsed:.2f}",
                    "model_state": mt_generator.dump_state(),
                },
                indent=2,
                ensure_ascii=False,
            )
        )


for mtin in tqdm(mt_inputs, desc="Generating multi-turn conversations"):
    generate_multi_turn(mtin)

Generating multi-turn conversations:   0%|          | 0/2010 [00:00<?, ?it/s]